### ISSUE TITLE
Rename combine?

### ISSUE THREAD

**Issue by nignatiadis** [juliangehring/MultipleTesting.jl#48]
Loading in both `MultipleTesting.jl` and `DataFrames.jl` yields the following warning:

`WARNING: using DataFrames.combine in module Main conflicts with an existing identifier.`

Do you think we should rename `combine`? For example, p-value combination seems to be more common in the bioinformatics literature, but in statistics people call it a global test instead. What do you think about moving to the latter (e.g. call it `globaltest` or something similar)?

**Comment by juliangehring** [comment]
I'm not sure what the best strategy may be. It is rather unfortunate that there is no better way of handling clashing method names in julia when they have different signatures and there is no ambiguity which one to use. Here my two cents:

1. Add ´DataFrames´ as a dependency and extend the existing ´combine´ method: This should work, but it seems like overkill to me (since DataFrames has quite a few dependencies and we don't need any other functionality of it)
2. Leave as is and hope that nobody wants to use the two packages together...
3. Use submodules: Separate the different functionalities of the packages in submodules, and ask the user to load them as needed. This way, one could avoid the clash in cases where the p-value combination part is not directly used; e.g. if I'm only interested in p-value adjustment, I load that submodule and don't have to face the clashing methods. However, that doesn't really address the issue in case I do want the p-value combination together with data frames.
4. Rename the method: Okay, we should probably really do this. But can we perhaps use a verb as the new name, instead of e.g. ´globaltest´? I like the idea of using (simple) verbs for methods/functions (that do something), and nouns for the statistical methods. And which name could we choose that wouldn't clash with methods in other (stats) packages? ´combine_statistics´ may work, but this also seems rather lengthy.

In any way, I'm open for any kind of solution.

**Comment by nignatiadis** [comment]
Hi Julian,

I agree no solution seems perfect. `combine` sounds nice indeed, although something like `aggregate` could also work. Or if we find more reasonable use cases for such verbs, we could discuss in StatsBase.jl so that it gets in there.  So I'd go with 2 for now and figure out how much of a problem this is along the way.

Another approach would be to just implement these as actual hypothesis tests as in `HypothesisTests.jl`, although I am not sure how much I like that interface either..

Nikos

**Comment by juliangehring** [comment]
I like `aggregate`, but we face the same problem as before: It is a [method](https://juliadata.github.io/DataFrames.jl/stable/lib/functions.html#DataFrames.aggregate) in `DataFrames`.

Let's leave it for now as is and look for good alternatives while we go forward. If we could solve this by integrating better with other packages, that would of course be neat.

**Comment by juliangehring** [comment]
Since julia v1.0, the warning is has become more informative:
> WARNING: both MultipleTesting and DataFrames export "combine"; uses of it in module Main must be qualified
The correct method can now be chosen with `MultipleTesting.combine()` or `DataFrames.combine()`.
@nignatiadis Can we close this issue?

**Comment by juliangehring** [comment]
I don't consider this to be an issue in current julia versions. Please feel free to reopen if needed
